<?xml version="1.0"?>
<xacro:macro name="mbot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 常量定义 -->
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_separation" value="0.25" />
  <!-- <xacro:property name="base_length" value="0.2" /> -->
  <!-- <xacro:property name="base_width" value="0.15" /> -->
  <xacro:property name="base_radius" value="0.175" />
  <!-- <xacro:property name="base_width" value="0.15" /> -->
  <xacro:property name="base_height" value="0.05" />

  <xacro:property name="lidar_height" value="0.02" />
  <xacro:property name="lidar_radius" value="0.05" />

  <!-- 颜色定义 -->
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0" />
  </material>
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0" />
  </material>

  <!-- 底盘 -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length = "${base_height}"/>
      </geometry>
      <material name="orange" />
    </visual>
    <collision>
      <geometry>
         <cylinder radius="${base_radius}" length = "${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0" />
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.01" />
    </inertial>
  </link>

  <!-- 左轮 -->
  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="black" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>
    <inertial>
      <mass value="0.1" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

  <!-- 右轮 -->
  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="black" />
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>
    <inertial>
      <mass value="0.1" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </link>

    <!-- 被动轮（万向轮） -->
  <link name="caster_wheel_link">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius/2}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius/2}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
               iyy="0.0001" iyz="0.0"  
               izz="0.0001" />
    </inertial>
  </link>

  <!-- 激光雷达连杆 -->
  <link name="laser_link">
    <!-- 视觉模型：模拟雷达外观（圆柱形） -->
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}" /> <!-- 雷达半径0.05m，高度0.1m -->
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0" /> <!-- 灰色雷达外壳 -->
      </material>
      <origin xyz="0 0 0" rpy="0 0 0" /> <!-- 雷达自身坐标系原点 -->
    </visual>
    
    <!-- 碰撞模型：与视觉模型一致，避免碰撞 -->
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_radius}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    
    <!-- 惯性参数：雷达质量轻，惯性小 -->
    <inertial>
      <mass value="0.2" /> <!-- 雷达质量0.2kg -->
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
              iyy="0.001" iyz="0.0" 
              izz="0.001" /> <!-- 简化的转动惯量 -->
    </inertial>
  </link>

  <!-- IMU连杆 -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01" /> <!-- 尺寸：0.05m x 0.05m x 0.02m -->
      </geometry>
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1.0" /> <!-- 银色外观 -->
      </material>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    
    <collision>
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    
    <inertial>
      <mass value="0.05" /> <!-- 质量50克 -->
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
              iyy="0.0001" iyz="0.0" 
              izz="0.0001" /> <!-- 简化的惯性矩阵 -->
    </inertial>
  </link>

  <!-- 左轮关节 -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel_link" />
    <origin xyz="-0.05 ${wheel_separation/2} -${wheel_radius/2}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- 右轮关节 -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel_link" />
    <origin xyz="-0.05  -${wheel_separation/2} -${wheel_radius/2}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

   <!-- 被动轮关节 -->
  <joint name="caster_joint" type="continuous">
    <parent link="base_link" />
    <child link="caster_wheel_link" />
    <origin xyz="${base_radius-wheel_radius/2} 0 -${wheel_radius}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <!-- 雷达关节：固定在底盘顶部 -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link" /> <!-- 父连杆：机身底盘 -->
    <child link="laser_link" /> <!-- 子连杆：雷达 -->
    <!-- 安装位置：底盘中心正上方，距离底盘顶部0.1m（避免遮挡） -->
    <origin xyz="0 0 ${base_height/2 + lidar_height/2}" rpy="0 0 0" />
    <!-- 说明：
      - x=0, y=0：位于底盘中心
      - z=${base_height/2 + 0.1}：底盘自身高度的一半（base_height/2）加上0.1m的抬高，确保雷达远离机身
    -->
  </joint>

  <!-- IMU关节：固定在底盘中心上方 -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <!-- 说明：
      - x=0, y=0：位于底盘中心
      - z=${base_height/2 + 0.01}：在底盘顶部上方0.01m处
    -->
  </joint>
  
  <!-- 里程计框架 -->
  <link name="odom" />
  <joint name="odom_joint" type="fixed">
    <parent link="odom" />
    <child link="base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>
</xacro:macro>