<?xml version="1.0"?>
<robot name="mbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 包含基础结构 -->
  <xacro:include filename="mbot_base.urdf.xacro" />
  <!-- <xacro:mbot_base /> -->
  <!-- Gazebo插件配置 -->
  <gazebo>
    <plugin name="differential_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/mbot</namespace>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <max_wheel_speed>2.0</max_wheel_speed>
      <torque>10.0</torque>
      
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="ground_truth_plugin" filename="libgazebo_ros_p3d.so">
       <ros>
            <namespace>/mbot</namespace>
            <remapping>odom:=gazebo_pose</remapping>
       </ros>
      <frame_name>world</frame_name>
      <body_name>base_link</body_name>
      <update_rate>50.0</update_rate>
      <gaussian_noise>0</gaussian_noise>
    </plugin>
  </gazebo>

  <!-- 在URDF末尾添加Gazebo雷达插件 -->
  <gazebo reference="laser_link"> <!-- 关联雷达连杆 -->
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose> <!-- 雷达自身姿态（无偏移） -->
      <visualize>false</visualize> <!-- 在Gazebo中可视化雷达射线 -->
      
      <!-- 雷达参数 -->
      <update_rate>10</update_rate> <!-- 刷新率10Hz -->
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples> <!-- 水平方向360个点 -->
            <resolution>1.0</resolution> <!-- 角度分辨率1度 -->
            <min_angle>0</min_angle> <!-- 起始角度0度 -->
            <max_angle>6.28319</max_angle> <!-- 终止角度2π（360度） -->
          </horizontal>
        </scan>
        <range>
          <min>0.1</min> <!-- 最小探测距离0.1m -->
          <max>10.0</max> <!-- 最大探测距离10m -->
          <resolution>0.01</resolution> <!-- 距离分辨率0.01m -->
        </range>
      </ray>
      
      <!-- ROS插件：将雷达数据发布为LaserScan消息 -->
      <plugin name="laser_plugin" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/mbot</namespace> <!-- 命名空间 -->
          <remapping>scan:=laser/scan</remapping> <!-- 发布话题：/mbot/laser/scan -->
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type> <!-- 消息类型 -->
      </plugin>
    </sensor>
  </gazebo>

  <!-- IMU传感器插件 -->
  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>100</update_rate> <!-- 更新频率100Hz -->
      <visualize>false</visualize> <!-- 不显示可视化射线 -->
      
      <!-- IMU噪声参数（可根据实际传感器调整） -->
      <linear_acceleration>
        <noise type="gaussian">
          <mean>0.0</mean>
          <stddev>0.01</stddev> <!-- 加速度噪声标准差 -->
          <bias_mean>0.0</bias_mean>
          <bias_stddev>0.001</bias_stddev>
        </noise>
      </linear_acceleration>
      
      <angular_velocity>
        <noise type="gaussian">
          <mean>0.0</mean>
          <stddev>0.005</stddev> <!-- 角速度噪声标准差 -->
          <bias_mean>0.0</bias_mean>
          <bias_stddev>0.0001</bias_stddev>
        </noise>
      </angular_velocity>
      
      <!-- ROS插件：发布IMU消息 -->
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <namespace>/mbot</namespace> <!-- 命名空间 -->
          <remapping>imu/data_raw:=imu/data_raw</remapping> <!-- 原始IMU数据 -->
          <remapping>imu/data:=imu/data</remapping> <!-- 处理后的IMU数据 -->
          <remapping>imu/temperature:=imu/temperature</remapping> <!-- 温度数据 -->
        </ros>
        
        <!-- 插件参数 -->
        <frame_name>imu_link</frame_name> <!-- 坐标系名称 -->
        <topic>imu/data</topic> <!-- 主话题名 -->
        <queue_size>10</queue_size>
        <gaussian_noise>0.0</gaussian_noise> <!-- 全局噪声系数 -->
        <update_rate>100.0</update_rate> <!-- 发布频率 -->
      </plugin>
    </sensor>
  </gazebo>
</robot>